FA.JustBlog/FA.JustBlog.View/Controllers/HomeController.cs
using FA.JustBlog.Core.Repositories;
using FA.JustBlog.View.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace FA.JustBlog.View.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly PostRepository _postRespository;
        private readonly CategoryRepository _categoryRepository;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
            _categoryRepository = new CategoryRepository();
            _postRespository = new PostRepository();
        }

        public IActionResult Index()
        {
            var lstPost = _postRespository.GetAllPosts();
            return View(lstPost);
        }

        public IActionResult Privacy()
        {
            return View();
        }
        public IActionResult About()
        {
            return View();
        }

        //Get post order by PostOn
        public IActionResult PostOrderByPostOn()
        {
            var lstPost = _postRespository.GetAllPosts().OrderBy(x => x.PostedOn);
            return View("Index", lstPost);
        }

        //Get MostViewedPosts
        public IActionResult MostViewedPosts()
        {
            var lstPost = _postRespository.GetMostViewedPost(5);
            return View("Index", lstPost);
        }

        //Get most 5 interested post
        public IActionResult MostInterestedPosts()
        {
            var lstPost = _postRespository.GetAllPosts().OrderByDescending(post => post.TotalRate).Take(5);
            return View("Index", lstPost);
        }

        //Get published post
        public IActionResult GetPublishedPost()
        {
            var lstPost = _postRespository.GetAllPosts().Where(x => x.Published);
            return View("Index", lstPost);
        }

        //Get Unpublished post
        public IActionResult GetUnpublishedPost()
        {
            var lstPost = _postRespository.GetAllPosts().Where(x => !x.Published);
            return View("Index", lstPost);
        }

        //Get post by category
        public IActionResult PostByCategory(string categoryName)
        {
            var lstPost = _postRespository.GetPostsByCategory(categoryName);
            return View("Index", lstPost);
        }

        //Get post by year month
        [HttpGet("post/{year:int}/{month:int}/{title}")]
        public IActionResult PostByMonthYear(int year, int month, string title)
        {
            var post = _postRespository.FindPost(year, month, title);
            if (post == null)
            {
                return NotFound();
            }
            var category = _categoryRepository.Find(post.CategoryId);
            ViewData["Category"] = category.Name;
            return View("Details", post);
        }



        //Get post by tag
        public IActionResult GetPostByTag(string tagName)
        {
            var lstPost = _postRespository.GetPostsByTag(tagName);
            return View("Index", lstPost);
        }



        // GET: Post/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = _postRespository.FindPost((int)id);
            var category = _categoryRepository.Find(post.CategoryId);
            ViewData["Category"] = category.Name;

            return View(post);
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        public ActionResult AboutCard()
        {
            return PartialView("_PartialAboutCard");
        }
        public ActionResult ListPostMostView()
        {
            var lstPost = _postRespository.GetMostViewedPost(5);
            return PartialView("_ListPosts", lstPost);
        }
    }
}

FA.JustBlog/FA.JustBlog.View/ViewComponents/ListPostViewComponent.cs
using FA.JustBlog.Core.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace FA.JustBlog.View.ViewComponents
{
    public class ListPostViewComponent : ViewComponent
    {
        private readonly PostRepository _postRespository;
        public ListPostViewComponent()
        {
            _postRespository = new PostRepository();
        }
        public IViewComponentResult Invoke()
        {
            var lstPost = _postRespository.GetHighestPosts(5);
            return View(lstPost);
        }
    }
}

FA.JustBlog/FA.JustBlog.View/Views/Home/About.cshtml
<div class="col-lg-3 mx-auto">
    @Html.Partial("_PartialAboutCard")
    @await Component.InvokeAsync("ListPost")
</div>
@{
}

FA.JustBlog/FA.JustBlog.View/Views/Home/Details.cshtml
@model FA.JustBlog.Core.Models.Post

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Post</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-5">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-5">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-5">
            @Html.DisplayNameFor(model => model.ShortDescription)
        </dt>
        <dd class="col-sm-5">
            @Html.DisplayFor(model => model.ShortDescription)
        </dd>
        <dt class="col-sm-5">
            @Html.DisplayNameFor(model => model.PostContent)
        </dt>
        <dd class="col-sm-5">
            @Html.DisplayFor(model => model.PostContent)
        </dd>
        <dt class="col-sm-5">
            @Html.DisplayNameFor(model => model.UrlSlug)
        </dt>
        <dd class="col-sm-5">
            @Html.DisplayFor(model => model.UrlSlug)
        </dd>
        <dt class="col-sm-5">
            @Html.DisplayNameFor(model => model.Published)
        </dt>
        <dd class="col-sm-5">
            @Html.DisplayFor(model => model.Published)
        </dd>
        <dt class="col-sm-5">
            @Html.DisplayNameFor(model => model.PostedOn)
        </dt>
        <dd class="col-sm-5">
            @Html.DisplayFor(model => model.PostedOn)
        </dd>
        <dt class="col-sm-5">
            @Html.DisplayNameFor(model => model.Modified)
        </dt>
        <dd class="col-sm-5">
            @Html.DisplayFor(model => model.Modified)
        </dd>
        <dt class="col-sm-5">
            @Html.DisplayNameFor(model => model.ViewCount)
        </dt>
        <dd class="col-sm-5">
            @Html.DisplayFor(model => model.ViewCount)
        </dd>
        <dt class="col-sm-5">
            @Html.DisplayNameFor(model => model.RateCount)
        </dt>
        <dd class="col-sm-5">
            @Html.DisplayFor(model => model.RateCount)
        </dd>
        <dt class="col-sm-5">
            @Html.DisplayNameFor(model => model.TotalRate)
        </dt>
        <dd class="col-sm-5">
            @Html.DisplayFor(model => model.TotalRate)
        </dd>
        <dt class="col-sm-5">
            Category
        </dt>
        <dd class="col-sm-5">
            @ViewData["Category"]
        </dd>

    </dl>
</div>
<div>
    <a asp-action="Index" class="btn btn-primary">Back to List</a>
</div>

FA.JustBlog/FA.JustBlog.View/Views/Home/Index.cshtml
@model IEnumerable<FA.JustBlog.Core.Models.Post>
@using FA.JustBlog.View.HTMLHelper

@{
    ViewData["Title"] = "Index";
}

<h1>All posts!</h1>
<hr />
<div>
    <a class="btn btn-success" asp-action="PostOrderByPostOn">Order post by post on</a>
    <a class="btn btn-success" asp-action="Index">Order post normal</a>
</div>

@foreach (var post in Model)
{
    <div class="post-preview">

        @Html.ActionLink(
                linkText: post.Title,
                actionName: "PostByMonthYear",
                controllerName: "Home",
                routeValues: new
                {
                    year = post.PostedOn.Year,
                    month = post.PostedOn.Month.ToString("00"),
                    title = post.UrlSlug
                },
                htmlAttributes: null
                )

        <p class="post-meta">
            Posted @Html.GetFriendlyDateTimeValue(post) Viewed @post.ViewCount time(s) with Rate @post.RateCount
        </p>
        <p>@post.ShortDescription</p>
        @{
            var category = Html.GetCategory(post);
            if (category != null)
            {
                <p>Category: <a href="@Url.Action("PostByCategory", "Home", new { categoryName = category.Name })">@category.Name</a></p>

            }
            var lstTag = Html.GetTags(post);
            if (lstTag != null && lstTag!.Count != 0)
            {
                <p>
                    Tags:
                    @foreach (var tag in lstTag)
                    {
                        <a class="btn btn-dark" href="@Url.Action("GetPostByTag", "Home", new { tagName = tag.Name })">@tag.Name</a>
                    }
                </p>
            }
            else if (lstTag!.Count == 0 || lstTag == null)
            {
                <p>Tags: No tag</p>

            }
        }
    </div>
    <!-- Divider-->
    <hr class="my-4" />
}

FA.JustBlog/FA.JustBlog.View/Views/Home/_PartialAboutCard.cshtml
<div class="card" style="width: 18rem;">
    <img src="/img/about-bg.jpg" class="card-img-top" alt="about me">
    <div class="card-body">
        <h5 class="card-title">About Me!</h5>
        <p class="card-text">Just me, my self and I, exploring the universe of uknowment. I have a heart of love and a interest</p>
    </div>
</div>