FA.JustBlog/FA.JustBlog.View/Areas/Admin/Controllers/TagController.cs
using FA.JustBlog.Core.Models;
using FA.JustBlog.Core.Repositories;
using FA.JustBlog.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FA.JustBlog.View.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = $"{SD.CONTRIBUTER_ROLE}, {SD.USER_ROLE}, {SD.BLOGOWNER_ROLE}")]
    public class TagController : Controller
    {
        private readonly TagRepository _tagRepository;

        public TagController()
        {
            _tagRepository = new TagRepository();
        }

        // GET: Tag
        public IActionResult Index()
        {
            var lstTag = _tagRepository.GetAllTags();
            return View(lstTag);
        }

        // GET: Tag/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tag = _tagRepository.Find((int)id);

            return View(tag);
        }

        //Get tag by name
        public IActionResult GetTagByName(string name)
        {
            var tag = _tagRepository.GetTagByUrlSlug(name);
            return View("Details", tag);
        }

        // GET: Tag/Create
        [Authorize(Roles = $"{SD.CONTRIBUTER_ROLE}, {SD.BLOGOWNER_ROLE}")]
        public IActionResult Create()
        {
            return View();
        }



        // POST: Tag/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = $"{SD.CONTRIBUTER_ROLE}, {SD.BLOGOWNER_ROLE}")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Id,Name,UrlSlug,Description,Count")] Tag tag)
        {
            tag.Count = 0;
            if (ModelState.IsValid)
            {
                _tagRepository.AddTag(tag);
                return RedirectToAction(nameof(Index));
            }
            return View(tag);
        }

        // GET: Tag/Edit/5
        [Authorize(Roles = $"{SD.CONTRIBUTER_ROLE}, {SD.BLOGOWNER_ROLE}")]
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tag = _tagRepository.Find((int)id);
            if (tag == null)
            {
                return NotFound();
            }
            return View(tag);
        }

        // POST: Tag/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = $"{SD.CONTRIBUTER_ROLE}, {SD.BLOGOWNER_ROLE}")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Id,Name,UrlSlug,Description,Count")] Tag tag)
        {
            if (id != tag.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _tagRepository.UpdateTag(tag);
                }
                catch
                {
                    throw;
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tag);
        }

        // GET: Tag/Delete/5
        [Authorize(Roles = $"{SD.BLOGOWNER_ROLE}")]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tag = _tagRepository.Find((int)id);
            if (tag == null)
            {
                return NotFound();
            }
            _tagRepository.DeleteTag(tag);

            return RedirectToAction(nameof(Index));
        }
        #region Get API


        public IActionResult GetAllTagsJson()
        {
            var lstTag = _tagRepository.GetAllTags();
            return Json(new { data = lstTag });
        }
        #endregion

    }
}

FA.JustBlog/FA.JustBlog.View/ViewComponents/ListTagTopTenViewComponent.cs
using FA.JustBlog.Core.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace FA.JustBlog.View.ViewComponents
{
    public class ListTagTopTenViewComponent : ViewComponent
    {
        private readonly TagRepository _tagRepository;
        public ListTagTopTenViewComponent()
        {
            _tagRepository = new TagRepository();
        }
        public IViewComponentResult Invoke()
        {
            var tags = _tagRepository.GetTopTag(10);
            return View(tags);
        }
    }
}

FA.JustBlog/FA.JustBlog.View/Areas/Admin/Views/Tag/Create.cshtml
@model FA.JustBlog.Core.Models.Tag

@{
    ViewData["Title"] = "Create";
    Layout = "/Areas/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Tag</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UrlSlug" class="control-label"></label>
                <input asp-for="UrlSlug" class="form-control" />
                <span asp-validation-for="UrlSlug" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Count" class="control-label"></label>
                <input asp-for="Count" class="form-control" />
                <span asp-validation-for="Count" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FA.JustBlog/FA.JustBlog.View/Areas/Admin/Views/Tag/Details.cshtml
@model FA.JustBlog.Core.Models.Tag

@{
    ViewData["Title"] = "Details";
    Layout = "/Areas/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Tag</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UrlSlug)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UrlSlug)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Count)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Count)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

FA.JustBlog/FA.JustBlog.View/Areas/Admin/Views/Tag/Edit.cshtml
@model FA.JustBlog.Core.Models.Tag

@{
    ViewData["Title"] = "Edit";
    Layout = "/Areas/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Tag</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UrlSlug" class="control-label"></label>
                <input asp-for="UrlSlug" class="form-control" />
                <span asp-validation-for="UrlSlug" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Count" class="control-label"></label>
                <input asp-for="Count" class="form-control" />
                <span asp-validation-for="Count" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FA.JustBlog/FA.JustBlog.View/Areas/Admin/Views/Tag/Index.cshtml
@model IEnumerable<FA.JustBlog.Core.Models.Tag>

@{
    ViewData["Title"] = "Index";
    Layout = "/Areas/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create" asp-area="Admin">Create New</a>
</p>
<table id="tagTable" class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>
                Tag name
            </th>
            <th>
                Url slug
            </th>
            <th>Count</th>
            <th></th>
        </tr>
    </thead>
    <tbody>

    </tbody>
    <tfoot>
        <tr>
            <th>
                Tag name
            </th>
            <th>
                Url slug
            </th>
            <th>Count</th>
        </tr>
    </tfoot>
</table>


@await Component.InvokeAsync("ListTagTopTen")

@section Scripts {
    <script>
        $(document).ready(function () {
            loadDataTable();
        });

        function loadDataTable() {
            dataTable = $('#tagTable').DataTable({
                "ajax": { url: '/admin/tag/GetAllTagsJson' },
                "columns": [
                    { "data": "name", "width": "20%" },
                    { "data": "urlSlug", "width": "20%" },
                    { "data": "count", "width": "20%" },
                    {
                        "data": "id",
                        "render": function (data) {
                            return `<div class="text-center">
                                                <a href="/admin/tag/details/${data}" class="btn btn-primary text-white" style='cursor:pointer; '>Details</a>
                                                <a href="/admin/tag/edit/${data}" class='btn btn-success text-white' style='cursor:pointer; '>
                                            Edit
                                        </a>
                                                <a href="/admin/tag/Delete/${data}" class='btn btn-danger text-white' style='cursor:pointer; '>
                                            Delete
                                        </a>
                                    </div>`;
                        },
                        "width": "40%"
                    }
                ],
                initComplete: function () {
                    this.api()
                        .columns()
                        .every(function () {
                            let column = this;
                            let title = column.footer().textContent;

                            // Create input element
                            let input = document.createElement('input');
                            input.placeholder = title;
                            column.footer().replaceChildren(input);

                            // Event listener for user input
                            input.addEventListener('keyup', () => {
                                if (column.search() !== this.value) {
                                    column.search(input.value).draw();
                                }
                            });
                        });
                }
            })
        }
    </script>
}